export const ADD_USER_DATA = 'ADD_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const ADD_POSTS_DATA = 'ADD_POSTS_DATA';
export const REMOVE_POSTS_DATA = 'REMOVE_POSTS_DATA'
export const ADD_REMOVE_LIKE_FROM_POST = 'ADD_REMOVE_LIKE_FROM_POST';
export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';
